version: '3'

services:
  web:
    build: ./django_core
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_core:/django_core
    ports:
      - '8000:8000'

    environment:
      # Stripe specific keys
      - STRIPE_PUBLIC_KEY=pk_test_51PBtUHRr6GAVrD7HD0eeGsvT5Js8u8BN3uzmuC6JEIeD9NdVyNuoZI0NsgGLFRDUT6TnKsqHQwCmE6EXOhsaAsGy00zY8fnXVi
      - STRIPE_SECRET_KEY=sk_test_51PBtUHRr6GAVrD7HiyUZFSpEjMR93q18wEAp0BJfumlTKLN0rQp8ry1z9wj6jgUdD6nkcAvJeZosdLBJuSRKTUrQ00DoUG92QT
      - DJSTRIPE_TEST_WEBHOOK_SECRET=whsec_68c4a4df81109fe4efd2ccc3fa9310e752169c1bc87ddfd638c9b4b726e9fc7c
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672//

    depends_on:
      - celery
      - rabbit


  rabbit:
    image: rabbitmq:management

    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"


  celery:
    restart: always
    build: ./django_core
    command: celery -A myshop.celery worker -l info -P solo
    volumes:
      - ./django_core:/django_core

    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672//

    links:
      - rabbit
    depends_on:
      - rabbit


  stripe:
    image: stripe/stripe-cli:v1.19.4
    command: listen --api-key=sk_test_51PBtUHRr6GAVrD7HiyUZFSpEjMR93q18wEAp0BJfumlTKLN0rQp8ry1z9wj6jgUdD6nkcAvJeZosdLBJuSRKTUrQ00DoUG92QT --device-name=nikolay --forward-to=web:8000/payment/webhook/
    depends_on:
      - web

