# Generated by Django 5.0.4 on 2024-05-17 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='slug')),
                ('slug_en', models.CharField(max_length=200, null=True, unique=True, verbose_name='slug')),
                ('slug_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='shop_app_ca_name_c853a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('slug', models.CharField(max_length=200, verbose_name='slug')),
                ('slug_en', models.CharField(max_length=200, null=True, verbose_name='slug')),
                ('slug_ru', models.CharField(max_length=200, null=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='image')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_app.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='shop_app_pr_id_4c20f0_idx'), models.Index(fields=['name'], name='shop_app_pr_name_673a26_idx'), models.Index(fields=['-created'], name='shop_app_pr_created_34f5a9_idx')],
            },
        ),
    ]
