# Generated by Django 5.0.4 on 2024-05-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.CharField(max_length=200, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='slug'),
        ),
    ]
