# Generated by Django 5.0.4 on 2024-05-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='second_name',
            field=models.CharField(max_length=50, null=True, verbose_name='second_name'),
        ),
    ]
